export const Teams = [
  {name: "Team English",},
  {name: "Team Mathematics",},
  {name: "Team Civic",},
  {name: "Team Yoruba",},
  {name: "Team Quantitative",},
  {name: "Team Hausa",},
  {name: "Team Agric",},
  {name: "Team Igbo",},
  {name: "Team Verbal",},
  {name: "Team Vocational",},
  {name: "Team P.H.E",},
  {name: "Team IRK",},
  {name: "Team Computer",},
  {name: "Team CRK",},
  {name: "Team Social Studies",},
  {name: "Team Home Economics",},
  {name: "Team Basic Science",},
  {name: "Team Handwriting",},
  {name: "Team Fine Art",},
  {name: "Team Literature In English",},
  {name: "Team C.C.A",},
  {name: "Team Business Studies",},
  {name: "Team Music",},
  {name: "Team Physics",},
  {name: "Team Chemistry",},
  {name: "Team Biology",},
  {name: "Team Commerce",},
  {name: "Team Account",},
  {name: "Team Government",},
  {name: "Team Book Keeping",},
  {name: "Team Economics",},
  {name: "Team Further Mathematics",},
  {name: "Team Phonics/Diction",},
  {name: "Team Data Proccessing",},
  {name: "Team French"},
]
